### PR TITLE
fix(layout_columns): Use `minmax(0, 1fr)` for column widths

### LINKED ISSUE #727: `layout_column_wrap()` doesn't force column width
If an element given to `layout_column_wrap()` has a set `width` that's greater than the allocated column width, that column is allowed to grow, throwing off the alignment of the remaining items in the row.

In the example below, the two elements should have equal widths that share the full row width.

```r
set.seed(1234)

page_fixed(
  div(class = "my-5"),
  layout_column_wrap(
    width = 1 / 2,
    div(
      class = "border border-danger",
      style = css(width = "400px", max_width = "100%"),
      lorem::ipsum(1, 1)
    ),
    div(
      class = "border border-primary",
      lorem::ipsum(1, 1)
    )
  ) |>
  tagAppendAttributes(
    class = "p-2 border border-secondary"
  )
)
```

image

The fix is to use `minmax(0, 1fr)`:

```patch
- grid-template-columns: 1fr 1fr;
+ grid-template-columns: repeat(2, minmax(0, 1fr));
```

```r
set.seed(1234)

page_fixed(
  div(class = "my-5"),
  layout_column_wrap(
    width = 1 / 2,
    div(
      class = "border border-danger",
      style = css(width = "400px", max_width = "100%"),
      lorem::ipsum(1, 1)
    ),
    div(
      class = "border border-primary",
      lorem::ipsum(1, 1)
    )
  ) |>
  tagAppendAttributes(
    class = "p-2 border border-secondary",
    style = css("grid-template-columns" = "repeat(2, minmax(0, 1fr))")
  )
)
```

image

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #727 

Background in this CSS tricks article: [Preventing a Grid Blowout](https://css-tricks.com/preventing-a-grid-blowout/)

Using `minmax(0, 1fr)` constrains each column to use up to `1fr`, otherwise the intrinsic width of one column can affect the sizes of other columns. (See the example in https://github.com/rstudio/bslib/issues/727#issuecomment-1666172356)

https://github.com/rstudio/bslib/assets/5420529/1408866f-2166-4680-b5b5-d7c1c829e9c3

### CODE REVIEW

File: R/layout.R [hunk 1]
```diff
@@ -69,7 +69,7 @@ layout_column_wrap <- function(
       if (num_cols != as.integer(num_cols)) {
         stop("Could not interpret width argument; see ?layout_column_wrap")
       }
-      paste0(rep_len("1fr", num_cols), collapse = " ")
+      sprintf("repeat(%s, minmax(0, 1fr))", num_cols)
     } else {
       if (fixed_width) {
         paste0("repeat(auto-fit, ", validateCssUnit(width), ")")
```
Comment (cpsievert) [inline R/layout.R:75]: Just curious, should we be doing the same here?

**Review by cpsievert — APPROVED** [review]
Great, thanks! Please add a news item

File: R/layout.R (hunk 1 above)
Comment (gadenbuie) [reply R/layout.R:75]: Do you mean in the `fixed_width` case? I don't think so, there we should have an absolute unit so we won't have the problems we run into when using `repeat(___, 1fr)`.

Comment (cpsievert) [reply R/layout.R:75]: Yep, and ok, thanks 👍
