### PR TITLE
fix: Only copy pre-compiled themes once

### LINKED ISSUE #1154: bslib dependencies fail during file copy when installed read-only
## Permission denied when using precompiled css from a read-only bslib installation

In enterprise settings it is not uncommon to have a centralized library of packages where everything is installed read-only and maintained by designated users/teams. Another use case which is quickly gaining popularity is using Nix package manager for maintaining data science environments. Nix also installs everything read-only.

https://github.com/rstudio/bslib/blob/b54bfb5de82f76bc044c4c661995af3a63e7ab29/R/bs-dependencies.R#L88

One solution would be to add `copy.mode = FALSE` to the `file.copy` calls, so that the file mode attributes are not preserved.

This fails in applications that call `bslib` internally, like `elmer`
```r
library(S7)
library(httr2)
library(coro)
library(shinychat)
library(elmer)

chat <- chat_ollama(
  model = 'zephyr7b',
  system_prompt = 'You are a friendly but terse coding assistant. You are an expert in R, Python, SQL.',
  echo = TRUE
)
elmer::live_browser(chat)
```

```
# UI error displayed:
An error occurred: inherits(pool, "curl_multi") is not TRUE
# Error in debugging:
Warning in file.copy(from, to, ...) :
  problem copying /path/to/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.eot to /path/to/tmp/bslib-precompiled-5/fonts/bootstrap/glyphicons-halflings-regular.eot: Permission denied
Warning in file.copy(from, to, ...) :
  problem copying /path/to/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.svg to /path/to/tmp/bslib-precompiled-5/fonts/bootstrap/glyphicons-halflings-regular.svg: Permission denied
Warning in file.copy(from, to, ...) :
  problem copying /path/to/R/librarybslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf to /path/to/tmp/bslib-precompiled-5/fonts/bootstrap/glyphicons-halflings-regular.ttf: Permission denied
Warning in file.copy(from, to, ...) :
  problem copying /path/to/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff to /path/to/tmp/bslib-precompiled-5/fonts/bootstrap/glyphicons-halflings-regular.woff: Permission denied
Warning in file.copy(from, to, ...) :
  problem copying /path/to/R/library/bslib/lib/bs3/assets/fonts/bootstrap/glyphicons-halflings-regular.woff2 to /path/to/tmp/bslib-precompiled-5/fonts/bootstrap/glyphicons-halflings-regular.woff2: Permission denied
```

Added here based on the issue raised on [elmer](https://github.com/tidyverse/ellmer/issues/244)

### PR DESCRIPTION
**Pull request by gadenbuie**
Currently, when a pre-compiled theme is used, we re-use `{tempdir()}/bslib-precompiled-5` but copy files from bslib to the temp directory every time the pre-compiled theme is used.

This PR refactors `bs_theme_dependencies()` to pull out the core logic (either use a precompiled theme or compile the theme via Sass) into helper functions, which clarifies the flow.

Then, if we've already prepared the full dependency in the temp directory, we re-use the prepared dependency on subsequent calls to `bs_theme_dependencies()`.

Closes #1154. The issue seen there arises when we copy files out of the package but the package is stored with all files having read-only (400) permissions. This doesn't cause problems until `bs_theme_dependencies()` is called for a second time, where we end up trying to overwrite existing files. This is a partial fix in the sense that `nix` will still complain about being unable to remove temp files, but we can't solve that entirely from bslib anyway.

### CODE REVIEW

File: R/bs-dependencies.R [hunk 1]
```diff
@@ -159,6 +98,90 @@ bs_theme_dependencies <- function(
...
+    return()
+  }
+
+  precompiled_css <- precompiled_css_path(theme)
+  if (is.null(precompiled_css)) {
+    return()
+  }
+
+  version <- theme_version(theme)
+  deps_hash <- rlang::hash(htmlDependencies(as_sass(theme)))
```
Comment (gadenbuie) [inline R/bs-dependencies.R:113]: This is probably over-thinking things. The one way that the theme could change between calls is if the Bootstrap JavaScript assets change. Taking the hash of the dependencies was intended to catch this, but we'd actually have to hash the files themselves. Not sure if it's worth it.

Comment (gadenbuie) [reply R/bs-dependencies.R]: Not hard, maybe still not worth it: 58f62cd46067c58462541ef2bbe37151a7a2cd1f

**Review by cpsievert — APPROVED** [review]

**Review by cpsievert — APPROVED** [review]

**Comment by ismirsehregal** [comment]
Just FYI: This also seems to fix a performance problem with the latest CRAN version:
https://stackoverflow.com/questions/79467288/how-to-speed-up-renderdt-with-bslib-in-shiny
I've seen repeated `file.copy` calls when profiling the app.
